{% set name = "cookiecutter-django" %}
{% set version = "2024.08.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cookiecutter/cookiecutter-django/archive/{{ version }}.tar.gz
  sha256: b09ba33a9e670b17094fcf3ccce19aa228dd085c560ac896ad515dae0fe7c63f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8
# https://github.com/cookiecutter/cookiecutter-django/blob/master/requirements.txt
# ------------------------------------------------------------------------------
    - cookiecutter >=2.6.0
    - sh >=2.0.7  # [unix]
    # Keep the package noarch but allow for the osx and linux only dep
    - __linux  # [linux]
    - __osx    # [osx]
    - __win    # [win]
    - binaryornot >=0.4.4
# Code quality
# ------------------------------------------------------------------------------
    #- black >=23.9.1
    #- isort >=5.12.0
    #- flake8 >=6.1.0
    - ruff >=0.6.3
    - django-upgrade >=1.20.0
    - djlint >=1.35.2
    - pre-commit >=3.8.0
# Testing
# ------------------------------------------------------------------------------
    - tox >=4.18.0
    - pytest >=8.3.2
    - pytest-xdist >=3.6.1
    - pytest-cookies >=0.7.0
    - pytest-instafail >=0.5.0
    - pyyaml >=6.0.2
# Scripting
# ------------------------------------------------------------------------------
    - pygithub >=2.4.0
    - gitpython >=3.1.43
    - jinja2 >=3.1.4
    - requests >=2.32.3
  run_constrained:
# Database
# ------------------------------------------------------------------------------
    - postgresql >=12.0,<17.0
    - sqlite >=3.46.0
    - psycopg-c >=3.2.1
    - psycopg >=3.2.1
# Docs
# ------------------------------------------------------------------------------
# https://github.com/cookiecutter/cookiecutter-django/blob/master/docs/requirements.txt
    - sphinx >=7.4.7
    - sphinx-rtd-theme >=2.0.0
    - myst-parser >=4.0.0
# Docker
# ------------------------------------------------------------------------------
    - docker-py >=6.0.0

test:
  imports:
    - cookiecutter
  commands:
    - cookiecutter cookiecutter-django --help
    - pip check
  requires:
    - pip

about:
  summary: A Cookiecutter template for creating production-ready Django projects quickly
  home: https://github.com/cookiecutter/cookiecutter-django
  description: |
    "Powered by Cookiecutter, Cookiecutter Django is a project template for jumpstarting 
    production-ready Django projects. The template offers a number of generation options, 
    we invite you to check the https://cookiecutter-django.readthedocs.io/en/latest/project-generation-options.html#template-options 
    to learn more about each of them."
  doc_url: https://cookiecutter-django.readthedocs.io/en/latest/
  dev_url: https://github.com/cookiecutter/cookiecutter-django
  license_family: BSD
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - rxm7706
